In [5]:
import pandas as pd
import numpy as np

In [6]:
forecast_df = pd.read_csv(
    r"C:\Users\91991\Desktop\internships\AMDOX\data\processed\m5_forecasting_dataset.csv"
)

C:\Users\91991\AppData\Local\Temp\ipykernel_22128\3314025340.py:1: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  forecast_df = pd.read_csv(

In [7]:
forecast_df.shape

(191300, 22)

In [8]:
forecast_df.shape

(191300, 22)

In [9]:
forecast_df["date"] = pd.to_datetime(
    forecast_df["date"]
)

In [10]:
forecast_df = forecast_df.sort_values(
    by=["id", "date"]
)

In [11]:
forecast_df["lag_7"] = forecast_df.groupby(
    "id"
)["sales"].shift(7)

In [12]:
forecast_df["lag_28"] = forecast_df.groupby(
    "id"
)["sales"].shift(28)

In [13]:
forecast_df["rolling_mean_7"] = forecast_df.groupby(
    "id"
)["sales"].transform(
    lambda x: x.shift(1).rolling(7).mean()
)

In [14]:
forecast_df["rolling_mean_28"] = forecast_df.groupby(
    "id"
)["sales"].transform(
    lambda x: x.shift(1).rolling(28).mean()
)

In [15]:
forecast_df["day_of_week"] = forecast_df[
    "date"
].dt.dayofweek

In [16]:
forecast_df["month"] = forecast_df[
    "date"
].dt.month

In [17]:
forecast_df["week"] = forecast_df[
    "date"
].dt.isocalendar().week

In [18]:
forecast_df["year"] = forecast_df[
    "date"
].dt.year

In [19]:
forecast_df["is_event"] = forecast_df[
    "event_name_1"
].notnull().astype(int)

In [20]:
forecast_df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,snap_TX,snap_WI,sell_price,lag_7,lag_28,rolling_mean_7,rolling_mean_28,day_of_week,week,is_event
20,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_1,0,2011-01-29,11101,...,0,0,2.18,NaN,NaN,NaN,NaN,5,4,0
120,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_2,1,2011-01-30,11101,...,0,0,2.18,NaN,NaN,NaN,NaN,6,4,0
220,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_3,0,2011-01-31,11101,...,0,0,2.18,NaN,NaN,NaN,NaN,0,5,0
320,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_4,0,2011-02-01,11101,...,1,0,2.18,NaN,NaN,NaN,NaN,1,5,0
420,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_5,4,2011-02-02,11101,...,0,1,2.18,NaN,NaN,NaN,NaN,2,5,0

In [21]:
forecast_df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,snap_TX,snap_WI,sell_price,lag_7,lag_28,rolling_mean_7,rolling_mean_28,day_of_week,week,is_event
20,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_1,0,2011-01-29,11101,...,0,0,2.18,NaN,NaN,NaN,NaN,5,4,0
120,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_2,1,2011-01-30,11101,...,0,0,2.18,NaN,NaN,NaN,NaN,6,4,0
220,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_3,0,2011-01-31,11101,...,0,0,2.18,NaN,NaN,NaN,NaN,0,5,0
320,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_4,0,2011-02-01,11101,...,1,0,2.18,NaN,NaN,NaN,NaN,1,5,0
420,FOODS_1_049_TX_2_validation,FOODS_1_049,FOODS_1,FOODS,TX_2,TX,d_5,4,2011-02-02,11101,...,0,1,2.18,NaN,NaN,NaN,NaN,2,5,0

In [22]:
forecast_df = forecast_df.dropna()

In [23]:
forecast_df.shape

(302, 29)

In [24]:
forecast_df.to_csv(
    r"C:\Users\91991\Desktop\internships\AMDOX\data\processed\forecasting_features.csv",
    index=False
)